# Generated by Django 5.2.7 on 2025-10-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub_app', '0002_course_remove_user_phone_no_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
