# Generated by Django 5.2.5 on 2025-11-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub_app', '0003_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='No instructor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='No instructor', max_length=200),
            preserve_default=False,
        ),
    ]
