# Generated by Django 5.2.5 on 2025-11-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub_app', '0008_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
